version: "3"

services:
  web:
    image: okcdbu/wordapi_web
    command: python manage.py runserver 0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/web
    depends_on:
      - db
  db:
    image: okcdbu/wordapi_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /data:/var/lib/postgresql/data/pgdata