# Generated by Django 3.2.6 on 2021-08-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('eng', models.CharField(max_length=30)),
                ('kor', models.TextField()),
                ('grade', models.CharField(max_length=20)),
            ],
        ),
    ]
